test_data={'image_jpg_file': PosixPath('testdata/files/image.jpg')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 100.0}
allure_results_dir=allure-results
os_info=Linux, 6.11.0-1018-azure
python_version=3.13.11 (main, Dec  8 2025, 02:51:34) [GCC 13.3.0]